[base]
cpu_step = 5
mem_step = 7

[sender]
trans_addr = "192.168.3.50:6000"
#trans_addr = "59.110.12.72:6000"
flush_interval = 3
max_sleep_time = 30

[[user_script]]
path = "./scripts/user.py"
step = 3